In [1]:
import torch
import numpy as np

In [2]:
x = np.array([2.0, 1.2, 4.5])
print(x)
print(type(x))

[2.  1.2 4.5]
<class 'numpy.ndarray'>


In [9]:
t_x = torch.Tensor(x)
print(t_x)
print(type(t_x))
print(t_x.type())

tensor([2.0000, 1.2000, 4.5000])
<class 'torch.Tensor'>
torch.FloatTensor


In [10]:
t_x32=torch.FloatTensor(np.float32(x))

print(t_x32)
print(type(t_x32))
print(t_x32.type())

tensor([2.0000, 1.2000, 4.5000])
<class 'torch.Tensor'>
torch.FloatTensor


In [11]:
print(t_x32.device)

cpu


In [1]:
%prun?

Docstring:
Run a statement through the python code profiler.

Usage, in line mode:
  %prun [options] statement

Usage, in cell mode:
  %%prun [options] [statement]
  code...
  code...

In cell mode, the additional code lines are appended to the (possibly
empty) statement in the first line.  Cell mode allows you to easily
profile multiline blocks without having to put them in a separate
function.

The given statement (which doesn't require quote marks) is run via the
python profiler in a manner similar to the profile.run() function.
Namespaces are internally managed to work correctly; profile.run
cannot be used in IPython because it makes certain assumptions about
namespaces which do not hold under IPython.

Options:

-l <limit>
  you can place restrictions on what or how much of the
  profile gets printed. The limit value can be:

     * A string: only information for function names containing this string
       is printed.

     * An integer: only these many lines are printed.

     *